version: "3.2"
services:
 redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    expose:
     - 6379
    volumes:
     - .:/var/lib/redis

    environment:
     - REDIS_REPLICATION_MODE=master

 app:
    build: ./
    expose:
      - 8000
    volumes:
      - .:/devops-app
    working_dir: /devops-app
    env_file:
      - .env
    command:
      sh -c 'ls'
      sh -c 'pip install -r requirments.txt'
      sh -c 'python tests/test.py'