version: "3.2"
services:
 redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    expose:
     - 6379
    volumes:
     - redis-data:/var/lib/redis

    environment:
     - REDIS_REPLICATION_MODE=master

 app:
    links:
      - redis
    build: ./
    expose:
      - 8000
    volumes:
      - app-data:/devops-app
    env_file:
      - .env
    command:
      sh -c 'pip install -r requirments.txt'

volumes:
    app-data:
        external: false
    redis-data:
        external: false
    