version: "3"
services:
 redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    expose:
     - 6379
    hostname: redis
    networks:
      - redis-net
    volumes:
     - .:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master

 app:
    links:
      - redis
    build: ./
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/devops-app
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
    command: ["${CMD}"]
    networks:
      - redis-net
networks:
  redis-net: