pipeline {
   agent any
   stages {
        stage('Init') {
            steps {
                script{
                    def BUILD_FULL = sh (
                        script: "docker-compose up",
                        returnStatus: true
                    ) == 0
                    echo "Build full flag: ${BUILD_FULL}"
                }
            }
        }
    }
}