def TEST_STATUS = false

pipeline {
   agent any
   stages {
        stage('app testing stage') {
            steps {
                script{
                    withEnv(["CMD=tests/test.py", "PORT=10000"]) {
                        TEST_STATUS = sh (
                            script: "docker-compose -p test up --build --abort-on-container-exit",
                            returnStatus: true
                        ) == 0
                    }
                }
            }
        }
        stage('app dev stage') {
            when{
                expression { TEST_STATUS }
            }
            steps {
                script{
                    withEnv(["CMD=hello.py", "PORT=10001"]) {
                        sh(
                            script: "docker-compose up -d --build"
                        )
                    }
                }
            }
        }
    }
}